name: Weekly Commit Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 0 * * 1" # Every Monday at 6:00 AM IST (which is 0:30 UTC)

jobs:
  run-scraper:
    if: ${{ github.event_name == 'schedule' || contains(github.event.head_commit.message, '#d2p') }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESSTOKEN }}
      EMAILID: ${{ secrets.EMAILID }}
      GITHUB_USERNAME: ${{ github.actor }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Use custom PAT for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug secrets
        run: |
          echo "Checking secrets:"
          echo "GITHUB_TOKEN is set: ${GITHUB_TOKEN:+yes}"
          echo "EMAILID is set: ${EMAILID:+yes}"

      - name: Run commit scraper script
        run: python gh-scrapper.py

      - name: Commit and push .mdx files
        run: |
          git config user.name "$GITHUB_USERNAME"
          git config user.email "$EMAILID"
          git add data/*.mdx
          if ! git diff --cached --quiet; then
            git commit -m "Update commit logs for $(date +'%Y-%m-%d')"
            git push https://"$GITHUB_USERNAME":${{ secrets.ACCESSTOKEN }}@github.com/${{ github.repository }} HEAD:main
          else
            echo "No changes to commit"
          fi
