name: Weekly Commit Scraper

on:
  schedule:
    - cron: "30 0 * * 1" # Every Monday at 6:00 AM IST (which is 0:30 UTC)

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESSTOKEN }}
      EMAILID: ${{ secrets.EMAILID }}
      GITHUB_USERNAME: ${{ github.actor }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Use custom PAT for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug secrets
        run: |
          echo "Checking secrets:"
          echo "GITHUB_TOKEN is set: ${GITHUB_TOKEN:+yes}"
          echo "EMAILID is set: ${EMAILID:+yes}"

      - name: Run commit scraper script
        run: python gh-scrapper.py

      - name: Commit and push .md files
        run: |
          git config user.name "$GITHUB_USERNAME"
          git config user.email "$EMAILID"

          NOW=$(TZ="Asia/Kolkata" date +'%A, %d %B %Y %H:%M')
          LAST_MONDAY=$(TZ="Asia/Kolkata" date -d "last monday 00:00:00" +'%A, %d %B %Y %H:%M')

          git add data/*.md

          if ! git diff --cached --quiet; then
            git commit -m "📝📅 Weekly commit sync. Duration: $LAST_MONDAY to $NOW"
            git push https://"$GITHUB_USERNAME":${{ secrets.ACCESSTOKEN }}@github.com/${{ github.repository }} HEAD:main
          else
            echo "No changes to commit"
          fi
